
window.addEventListener('load', function(){ // when the page loads, the functions runs
  console.log('5')
  loader1(); // loader1 function is called (see function below)
  document.getElementById('start').addEventListener('click', function() {
    bananaMasher(); // listens for a click on the start button and runs a function which calls bananamasher function
  })
});

function loader1() { // this function is called when the page loads (see above)
  console.log('4')
  for (var i = 0; i < 5; i++) { // for loop that runs 4 index values until less-than-five (4) is reached
    const p = document.createElement('p'); // creates a paragraph element
    p.innerText = "Loaded " + i + " items..."; // concatenates a string that prints a message in the previously-created paragraph element. i represents the current number generated by the for loop
    setTimeout(function() { document.body.appendChild(p) }, i * 1000); // adds the text contained in variable p at different second intervals: i times 1000 miliseconds. So 1 second mark, 2 second marks and so on. 
    if (i === 4) { // when we get to i === 4 in the for loop, end the loop
      console.log('get er done')
      setTimeout(allDone, 5000); // to be honest, fuzzy about what's going on here. we're calling setTimeout again and passing in 5000 so it will wait 5 seconds before running the allDone function (below). I think that's right.
    }
  }
}

function allDone() {
  console.log('3')
  alert('Done loading!'); // pop up alert tells the user that all the junk in loader1 is finished.
  document.getElementById('start').removeAttribute('disabled'); // enables the start button by removing the disabled attribute. that's handy!
}

// now we're done with the first part of the bananas program!

function bananaMasher() {
  console.log('2')
  var max = maxBananas() // calls the function maxBananas (see below)
  for (var i = 1; i < max ; i++) { // for loop that starts at one and continues to add 1 until it reaches one less than max, which is maxBananas (random number <8 + 2)
    const p = document.createElement('p'); // crates a paragraph element and stores it in variable p
    p.className = 'banana'; // add class="banana" to generated p so we can select it
    p.innerText = 'banana #' + i; // add concatenated string to generated p which tells us what number banana is being generated
    document.body.appendChild(p); // adds all the information from p to the document
  }
  alert('wait for it...'); // gives us a pop up telling the user to wait
  if (max > 2) { // if maxbananas is greater than 2, which it usually is, it runs the code in the code block
    console.log('did this run or what?')
    setTimeout(chomp, 1000); // setTimeout waits for one second before calling the chomp function (see below)
  }
}

function maxBananas() { // generates a random number between 1 and 8, and then adds 2 to that.
  console.log('6')
  return Math.floor(Math.random() * 8) + 2;
}


function chomp() {
  console.log('1')
  document.querySelectorAll('.banana')[0].remove(); // selects the element with class="banana" at the index 0 (the first one) and removes it from the list
  alert('yum yum all done'); // pop up telling the user that the program has eaten a banana
}
